extractMetadata/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('metadata.urls')),
    path('', include('django.contrib.auth.urls')),
    path(r'^download/(?P<path>.*)$', serve,
         {"document_root": settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

metadata/urls.py
from imp import get_magic
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'metadata'
urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("signup", views.signup, name="signup"),
    path("profile/<int:pk>", views.profile.as_view(), name="profile"),
    path("viewMetadata", views.view_metadata.as_view(), name="viewMetadata"),
    path("contact", views.contact, name="contact"),
    path("download", views.download_csv_data, name="download"),
    path("result", views.result, name="result"),
    path("save", views.save, name="save"),
    path("saved_files", views.saved_files.as_view(), name="saved_files"),
    path("review/<int:pk>", views.review, name="review"),
    path("history/<int:pk>", views.history.as_view(), name="history"),
    path("change_email/<int:pk>", views.change_email.as_view(), name="change_email"),
    path("update_picture", views.accountSettings, name='update_picture'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path("delete/<int:pk>", views.delete),
]

metadata/models.py
from bz2 import compress
from re import M
from stat import FILE_ATTRIBUTE_HIDDEN
from tkinter import N
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings


class Contact(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(
            2, "Name must be greater than 2 characters")]
    )
    email = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.message) < 15:
            return self.message
        return self.text[:11] + ' ...'


class Profile(models.Model):
    # Delete profile when user is deleted
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(
        default='default.jpg', upload_to='profile_pics', null=True, blank=True)

    def __str__(self):
        # show how we want it to be displayed
        return f'{self.user.username} Profile'

class History(models.Model):
    name = models.CharField(max_length=200)
    #size = models.IntegerField()
    data = models.TextField(null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Files(models.Model):
    file_name = models.CharField(max_length=200)
    uploaded_file = models.FileField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file_name

class other(models.Model):
    pass

metadata/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile


class FileUpload(forms.Form):
    upload_file = forms.FileField()


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

metadata/views.py
from posixpath import basename
import re
from urllib import response
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse_lazy, reverse
import os

from hachoir.parser import createParser
from hachoir.metadata import extractMetadata
import json
from django.http import JsonResponse
from django.http import HttpResponse
from django.utils.encoding import smart_str
from metadata.models import Contact, History, Files
from django.http import HttpResponseRedirect
from .forms import FileUpload, ProfileForm
from extractMetadata import settings

# import helper function defined in helper_functions.py
from .helperFuncs.extractImage import extract_image_metadata
from .helperFuncs.extractPdf import extract_pdf_file
from .helperFuncs.defaultMetadata import default_metadata
# from helperFuncs.pillow import extract_image_metadata_with_pillow

# ================
# import for csv
import csv

# Create your views here.

# =========
# import jsson to save the results
import json
# ===


def index(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        context = {'username': username}
    return render(request, "index.html", context)


# ==============================================
# =============================================
def about(request):
    return render(request, "about.html")


# ==========================================

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Invalid email or password')
            return redirect('metadata:login')
    return render(request, "login.html")


# ============================================
# ============================================


def logout(request):
    auth.logout(request)
    return redirect('/')


# =============================================
# =============================================


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        pass2 = request.POST['pass2']
        email = email.lower()
        if password == pass2:
            if User.objects.filter(email=email).exists():
                messages.info(request, "Email already exist")
                return redirect('metadata:signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, "Username already exist")
                return redirect('metadata:signup')
            else:
                user = User.objects.create_user(
                    username=username, first_name=first_name, last_name=last_name, email=email, password=password)
                user.save()
                messages.info(request, "Account created")
                return HttpResponseRedirect("login")
        else:
            messages.info(request, "Password didnt match")
            return redirect('metadata:signup')

    return render(request, "signup.html")


class profile(LoginRequiredMixin, View):
    login_url = '/login'
    success_url = reverse_lazy('metadata:profile')
    model = User
    template_name = 'profile.html'

    def get(self, request, pk):
        user = get_object_or_404(User, id=pk)
        return render(request, self.template_name)

    def post(self, request, pk):
        if request.POST['type'] == '1':
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            User.objects.filter(id=pk).update(
                first_name=first_name, last_name=last_name)
            messages.info(request, "Update Succcessful")
            return redirect('metadata:profile', pk=pk)
        else:
            username = request.POST['username']
            password1 = request.POST['pass1']
            password2 = request.POST['pass2']
            if password1 == password2:
                u = User.objects.get(username=username)
                u.set_password(password1)
                u.save()
                messages.info(request, "Password updated!!")
                user = auth.authenticate(username=username, password=password1)
                if user is not None:
                    auth.login(request, user)
                    return redirect('metadata:profile', pk=pk)

            else:
                messages.info(request, "Password did not match!!")
                return redirect('metadata:profile', pk=pk)


def handle_uploaded_file(f):
    with open('metadata / upload/'+f.name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


# ===========================================
# ==========================================

def contact(request):
    if request.method == 'POST':
        contact = Contact(
            name=request.POST['name'], email=request.POST['email'], message=request.POST['message'])
        contact.save()
        messages.info(request, "Message sent")
        return redirect('metadata:contact')
    return render(request, "contact.html")

# ==========================================
# ==========================================


class view_metadata(LoginRequiredMixin, View):
    success_url = reverse_lazy('metadata:viewMetadata')
    # template_name = 'metadata.html'
    template_name = 'extract.html'
    login_url = '/login'
    REDIRECT_FIELD_NAME = 'next'

    def post(self, request):
        form = FileUpload(request.POST, request.FILES)
        context = {"metadata": []}

        print("=====================")
        if form.is_valid():

            uploaded_file = request.FILES['upload_file']
            file_type = uploaded_file.content_type.split("/")
            print(uploaded_file)

            if file_type[0] == "video" or file_type[0] == "image" or file_type[0] == "audio":

                extracted_metadata = extract_image_metadata(
                    file_type[0], uploaded_file)
                context['metadata'] += extracted_metadata

            elif file_type[1].lower() == "pdf":
                pdf_metadata = extract_pdf_file(uploaded_file)
                context['metadata'] += pdf_metadata

            else:
                context['metadata'] += default_metadata(uploaded_file)

            request.session["metadata"] = context

            if uploaded_file.size < 20000000:
                name = uploaded_file.name
                owner = request.user
                file = Files.objects.filter(file_name=name).exists()

                if not file:
                    data = Files(file_name=name,
                                 uploaded_file=uploaded_file, owner=owner)
                    data.save()

            return redirect("metadata:result")
        return render(request, self.template_name, {'form': form})

    def get(self, request):
        form = FileUpload()
        return render(request, self.template_name, {'form': form})

# ================================================
# ================================================


def result(request):
    metadata = request.session.get("metadata")
    context = metadata
    return render(request, "result.html", context)


# ============================================
# ============================================
def save(request):
    metadata = request.session.get("metadata")
    name = metadata['metadata'][0]['tag_value']
    owner = request.user
    #size = metadata['metadata'][1]['tag_value']
    if History.objects.filter(name=name).exists() and History.objects.get(name=name).owner == owner:
        messages.info(request, "Data already present in your save history")
        return render(request, "index.html")
    else:
        data = json.dumps(metadata)
        history = History(data=data, name=name, owner=owner)
        history.save()
        messages.info(request, "data saved succesfully")
        return render(request, "index.html")

# ================


class saved_files(LoginRequiredMixin, View):
    login_url = '/login'
    model = Files
    template_name = 'saved_files.html'

    def get(set, request):
        owner = request.user
        files = Files.objects.all()
        context = {"owner": owner, "files": files}
        return render(request, "saved_files.html", context)


# ==============

def delete(request, pk):
    file = Files.objects.get(id=pk)
    file.delete()
    messages.info(request, f"file deleted succesfully")
    return redirect("/saved_files")

# ===============


def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path) as fh:
            response = HttpResponse(
                fh.read(), content_type="application/uploaded_file")
            response["Content-Disposition"] = "inline;filename" + \
                os.path.basename(file_path)
            return response

# =================


def review(request, pk):
    data = History.objects.get(id=pk)
    metadata = json.loads(data.data)
    context = metadata
    request.session["metadata"] = context
    return render(request, "result.html", context)


# ===============


class history(LoginRequiredMixin, View):
    login_url = '/login'
    success_url = reverse_lazy('metadata:history')
    model = History
    template_name = 'saved.html'

    def get(self, request, pk):
        user = request.user

metadata/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="../../static/css/style.css">
    {% block styles %}{% endblock styles %}
    <link href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@800,500,700,400,900&display=swap" rel="stylesheet">
</head>

<body>

    <header class="nav-head">
        <!-- Site logo -->
        <div class="nav-logo">
            <a href="/">
                <img src="../../static/images/deevr 2.png" class="site-logo">
            </a>
        </div>

        {% block nav %}
        <!-- Menu -->
        
        {% endblock %}

        <!-- nav buttons -->
        <div class="nav-button">
            <button class="nav-btn-outline">
                <a href="/login">Login</a>
            </button>

            <button class="nav-btn-solid">
                <a href="/signup">Get Started</a>
            </button>
        </div>

    </header>

    {% block content %}

    {% endblock %}




    <!-- Footer -->

    <footer>

        <div class="footer">

            <div class="footer1">

                <div class="footer1-top">
                    <a href="/">
                        <img src="../../static/images/deevr 2.png" alt="" class="footer-img">
                    </a>
                    <p class="footer-txt">Subscribe to keep up with the
                        latest news</p>
                </div>

                <div class="footer1-down">
                    <h2 class="footer-title">GET IN TOUCH</h2>

                    <div class="social-icons">
                        <img src="../../static/images/Facebook.png" alt="" class="social">
                        <img src="../../static/images/Twitter.png" alt="" class="social">
                        <img src="../../static/images/Linkedin.png" alt="" class="social">
                    </div>
                </div>

            </div>

            <div class="footer2">

                <h2 class="footer-title">Learn</h2>

                <nav class="footer-nav">
                    <a href="#">Our Product</a>
                    <a href="#">Tutorials</a>
                    <a href="#">Our Services</a>
                    <a href="#">Best Features</a>
                </nav>

            </div>

            <div class="footer3">

                <h2 class="footer-title">Company</h2>

                <nav class="footer-nav">
                    <a href="/about">About Us</a>
                    <a href="/contact">Contact Us</a>
                    <a href="/dashboard">Dashboard</a>
                    <a href="/viewMetadata">Extract Metadata</a>
                </nav>

            </div>

            <div class="footer4">

            </div>

        </div>

    </footer>

    <script src="../../static/javascript/extract.js"></script>
</body>

</html>

metadata/templates/base3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MetaData Extractor | Get detailed information on your files</title>
    <link rel="stylesheet" href="../../static/css/main.css" />
	<link rel="stylesheet" href="../../static/css/font.css">
	<link rel="stylesheet" href="../../static/css/login.css">
		<link href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@800,500,700,400,900&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="../../static/css/extract.css"> -->
    <!-- <link rel="stylesheet" href="../../static/css/about.css"> -->
  </head>
  <body>
    <header class="nav-head desktop-nav">
      <!-- Site logo -->
      <img src="../../static/images/deevr.svg" class="site-logo logo" />

      <!-- Menu -->
      <div class="navigation">
        <nav class="menu">
          <a href="index.html" class="active">Home</a>
          <a href="/contact">Contact</a>
          <a href="about">About Us</a>
          {% if user.is_authenticated %}
          <a href="dashboard.html">Dashboard</a>
          <a href="{% url 'metadata:profile' user.id %}">Profile</a>
          <a href="/logout">Logout</a>

          <a href="/viewMetadata">Extract MetaData</a>
          <a href="{% url 'metadata:history' user.id %}">Saved Metadatas</a>
          <a href="{% url 'metadata:saved_files' %}">Saved Files</a>
          {% else %}
          <a href="/login">Log in</a>
          <a href="/signup">Sign Up</a>
          {% endif %}
        </nav>
      </div>
    </header>

    <!-- Mobile Nav for Desktop View -->
    <header class="mobile-nav">
	<div class="container">

		<img src="../../static/images/Deevr-mobile.png" class="site-logo-sm logo" alt="site-logo" />
	</div>
      <!-- Menu -->
      <nav class="navigation container">
        <ul class="menu">
          <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="index.html" class="active">Home</a>
            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li>
          <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="/contact">Contact</a>
            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li>
          <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="about.html">About Us</a>

            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li>
          {% if user.is_authenticated %}
          <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="dashboard.html">Dashboard</a>
            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li>
          <!-- <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="{% url 'metadata:profile' user.id %}">Profile</a>
            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li> -->
          <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="/viewMetadata">Extract MetaData</a>
            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li>
          <!-- <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="{% url 'metadata:history' user.id %}">Saved Metadatas</a>
            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li>

          <li>
            <img src="../../static/images/School Building.png" alt="" />
            <a href="{% url 'metadata:saved_files' %}">Saved Files</a>
            <img class="arrow-icon" src="../../static/images/arrow-right.svg" alt="" />
          </li> -->
		  
			  <a href="/logout">Logout</a>
			  {% else %}
			  <a href="/login">Log in</a>
			  <a href="/signup">Sign Up</a>
			  {% endif %}

			<!-- nav buttons -->
			<div class="nav-button">
				<button class="nav-btn-outline">
					<a href="login.html">Login</a>
				</button>
			
				<button class="nav-btn-solid">
					<a href="register.html">Get Started</a>
				</button>
			</div>
        </ul>
      </nav>

     
    </header>

    {% block content %} {% endblock %}

    <footer class="container">
      <div>
        <div>
          <img src="css/img/deevr.svg" />
          <p>Subscribe to keep up with the<br />latest news</p>
        </div>
        <!--Social media handles-->
        <div>
          <h4><b>GET IN TOUCH</b></h4>
          <div class="media logos">
            <img src="" />
            <img src="" />
            <img src="" />
          </div>
        </div>
      </div>
      <div class="learn">
        <p><b>Learn</b></p>
        <div>
          <p>Our Product</p>
          <p>Tutorials</p>
          <p>Our Service</p>
          <p>Best Features</p>
        </div>
      </div>
      <div class="company">
        <p><b>Company</b></p>
        <div>
          <p>About Us</p>
          <p>Careers</p>
          <p>Contact Us</p>
          <p>News & Blog</p>
        </div>
      </div>
    </footer>
    <script src="../../static/javascript/script.js"></script>
  </body>
</html>

metadata/templates/change_email.html
<h2>Enter your new email below</h2>
{% for message in messages %}
<h5>{{message}}</h5>
{% endfor %}
<form action="{% url 'metadata:change_email' user.id %}" method="POST">
	{% csrf_token %}
	<label for="new_email">Enter your New email</label><br />
	<input type="text" name="new_email" /><br />
	<input type="submit" value="Change Email" /><br />
</form>

metadata/templates/contact.html
{% extends "base.html" %} {% block content %}

<h1>Contact Page</h1>

<form action="contact" , method="POST">
	{% csrf_token %}
	<label for="name">Name</label><br />
	<input type="text" name="name" required /><br />
	<label for="email">Email</label><br />
	<input type="email" name="email" required /><br />
	<label for="message">Message</label><br />
	<input type="textarea" name="message" required /><br />
	<input type="submit" />
</form>

{% endblock %}

metadata/templates/extract.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="../../static/css/extract.css">
{% endblock %}


{% block nav %}

<div class="navigation">
    <nav class="menu">
        <a href="/">Home</a>
        <a href="/about">About Us</a>
        <a href="/viewMetadata" class="active">Extract Metadata</a>
        <a href="/dashboard">Dashboard</a>
    </nav>
</div>

{% endblock %}

{% block content %}
<main>
    <!--Body-->

    <div class="section">
        <div class="hero">
            <div class="left-hero">
                <h2 class="hero-head">Extract <span>Metadata</span> <br>of Your <span>Desired</span> <br>File Type</h2>
            </div>

            <div class="right-hero">
                <div class="extract">
                    <div class="up">
                        <img src="../../static/css/img/document-upload.svg" class="img-svg upload">
                        <img src="../../static/images/document-cloud.svg" alt="" class="cloud hide-upload">
                        <p class="upload-text file-name"></p>
                    </div>
                    <form enctype="multipart/form-data" action="/viewMetadata" method="post">
                        {% csrf_token %}
                        <label for="id_upload_file" class="down" id="file-label">
                            <img src="../../static/css/img/cloud-plus.svg" class="img-svg">
                            <p class="upload-txt">Choose a File</p>
                            <div class="extract-input">
                                {{form}}
                            </div>
                        </label>
                        <button type="submit" class="metadata-btn hide-upload" id="metadata-btn">
                            Analyise file
                            <img src="../../static/images/bx_analyse.svg" alt="">
                        </button>
                    </form>
                </div>

            </div>

        </div>
    </div>

    <!--supported formats-->
    <h2 class="headline"><b>Supported Formats</b></h2>

    <div class="formats">

        <div class="card">
            <div class="icon-card">
                <h3><span>IMAGE</span> FILES</h3>
                <img src="../../static/css/img/Frame 1156.png" class="card-png">
            </div>
            <div class="text">
                <p class="card-text">JPEG,PNG,GIF,PSD,EPS,<br>PDF,AI,INDD,RAW,BMP,<br>TIFF</p>
            </div>
        </div>

        <div class="card">
            <div class="icon-card">
                <h3><span>PDF</span> FILES</h3>
                <img src="../../static/css/img/Frame 1167.png" class="card-png">
            </div>
            <div class="text">
                <p class="card-text">XML,XFA,Static PDF,<br>Dynamic forms,Traditional,<br>PDF for Archive</p>
            </div>
        </div>

        <div class="card">
            <div class="icon-card">
                <h3><span>JSON</span> FILES</h3>
                <img src="../../static/css/img/Frame 1156-1.png" class="card-png">
            </div>
            <div class="text">
                <p class="card-text">Number,String,Boolean,<br>Array,Object,Value,<br>Whitespace</p>
            </div>
        </div>
    </div>

</main>

{% endblock %}

metadata/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>MetaData Extractor | Get detailed information on your files</title>
	<link rel="stylesheet" href="../../static/css/main.css" />
	<link rel="stylesheet" href="../../static/css/font.css">
	<link rel="stylesheet" href="../../static/css/login.css">
	<link href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@800,500,700,400,900&display=swap" rel="stylesheet">
	<!-- <link rel="stylesheet" href="../../static/css/extract.css"> -->
	<!-- <link rel="stylesheet" href="../../static/css/about.css"> -->
</head>

<body>
	<section class="autentication-form">
		<div class="left-column" id="login-left">
			<img src="../../static/images/login-bg.png" alt="" />
		</div>
		<div class="right-column">
			<div class="form-header">
				<h1>Login</h1>

				<a href="/accounts/google/login/?process=login">
					<img src="../../static/images/google.png" alt="" class="google" />
					Sign in with Google
				</a>
				<a href="/accounts/github/login/?process=login">
					<img src="../../static/images/github.png" alt="" class="fb" />
					Sign in with Github
				</a>
			</div>
			<form action="login" method="post">
				{% csrf_token %}
				<div class="meta-form-field">
					<label for="username" class="field-label">Username</label>
					<input type="text" name="username" placeholder="username" />
				</div>
				<div class="form-field">
					<label for="password" class="field-label">Password</label>
					<input type="password" name="password" placeholder="Password" id="psw" />
					<span class="eye" onclick="myFunction()">
						<img src="../../static/images/eye.png" alt="" class="psw-icon" id="hide"/>
						<img src="../../static/images/eye-slash.png" alt="" class="psw-icon"  />
					</span>
				</div>

				<p class="login-password"><a href="#"> Forgot Password</a></p>
				
				<input type="submit" value="Login" />
				<input type="hidden" name="next" value="{{ next }}" />
			</form>

			<div>
				<p class="login-text">Don't have an account? <a href="signup"> Create Account</a></p>
			</div>
		</div>
	</section>
</body>
	/* overflow: hidden; */

</html>

metadata/templates/metadata.html
<!-- {% extends "base.html" %}

{% block content %} 


<form enctype="multipart/form-data" action="/viewMetadata" method="POST">
    {% csrf_token %}
    <p>Upload your file</p><br>
    {{form}} <br>
    <input type="submit" value="Submit">
</form>




{% endblock %} -->

metadata/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile Page{% endblock%} 
{% block content %}
 <div class="content-section">
      <div class="media">
		{% if user.profile.profile_pic %}
			<img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}" width="200" height="200">
		{% else %}
		<img class="rounded-circle account-img" src="{% static 'metadata/images/default.jpg'%}" width="200" height="200">
		{% endif %}
      </div>
	  <a href="/update_picture">Update Picture</a>
    </div>

<div class="head">
	{% for message in messages %}
	<h5>{{message}}</h5>
	{% endfor %}
	<h1>Account</h1>
	Email address <br />
	{{user.email}} <br />
	<a href="{% url 'metadata:change_email' user.id %}">change</a>
</div>
<div>
	<form action="{% url 'metadata:profile' user.id %}" method="POST">
		{% csrf_token %}
		<h3>Profile</h3>
		<p>First Name</p>
		<input
			type="text"
			placeholder="{{ user.first_name }}"
			name="first_name"
		/><br />
		<p>Last Name</p>
		<input
			type="text"
			placeholder="{{ user.last_name }}"
			name="last_name"
		/><br />
		<input type="submit" value="Save Changes" />
		<input type="hidden" name="type" value="1" />
	</form>
</div>

<div>
	<form action="{% url 'metadata:profile' user.id %}" method="POST">
		{% csrf_token %}
		<h3>Password</h3>
		<p>Enter Password</p>
		<input type="password" name="pass1" /><br />
		<p>Confirm Password</p>
		<input type="password" name="pass2" /><br />
		<input type="submit" value="Save Changes" />
        <input type="hidden" name="username" value="{{ user.username }}" />
		<input type="hidden" name="type" value="2" />
	</form>
</div>
{% endblock %}

metadata/templates/saved.html
{% extends "base.html" %} {% block content %}


<h2>Saved metadata </h2>
<table>
    <thead>
        <th>Date</th>
        <th>Filename</th>
    </thead>

{% for i in history %}
<tr></tr>
{% if i.owner == user%}
<td>{{ i.created_at }}</td>
<td>{{ i.name }} </td>
<td><a href="{% url 'metadata:review' i.id %}">View</a></td>
{% endif %}
</tr>
{% endfor %}

</table>
{% endblock %}